routes/admin.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ProjectController;
use App\Http\Controllers\Admin\TaskController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;


Route::get('/', [AdminController::class, 'index'])->name('home');

Route::group([
    'prefix' => 'users',
    'as' => 'users.'
], function () {
    Route::get('/', [UserController::class, 'index'])->name('index');
    Route::get('/create', [UserController::class, 'create'])->name('create');
    Route::post('/create', [UserController::class, 'store'])->name('store');
});

Route::group([
    'prefix' => 'projects',
    'as' => 'projects.'
], function () {
    Route::get('/', [ProjectController::class, 'index'])->name('index');
    Route::get('/create', [ProjectController::class, 'create'])->name('create');
    Route::post('/create', [ProjectController::class, 'store'])->name('store');
});

Route::group([
    'prefix' => 'tasks',
    'as' => 'tasks.'
], function () {
    Route::get('/', [TaskController::class, 'index'])->name('index');
    Route::get('/create', [TaskController::class, 'create'])->name('create');
    Route::post('/create', [TaskController::class, 'store'])->name('store');
});

routes/user.php
<?php

use App\Http\Controllers\User\ActivityController;
use App\Http\Controllers\User\TaskController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect()->route('tasks.index');
})->name('home');

Route::group([
    'prefix' => 'tasks',
    'as' => 'tasks.'
], function() {
    Route::get('/', [TaskController::class, 'index'])->name('index');

    Route::group([

    ], function () {
        Route::get('/{id}/activity/create', [ActivityController::class, 'create'])->name('activity.create');
        Route::post('/{id}/activity/create', [ActivityController::class, 'store'])->name('activity.store');
    });
});

Route::group([
    'prefix' => 'activities',
    'as' => 'activities.'
], function() {
    Route::get('/', [ActivityController::class, 'index'])->name('index');
    Route::post('/user', [ActivityController::class, 'byUser'])->name('user');
});

routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\ProjectController;
use App\Http\Controllers\Admin\TaskController;
use App\Http\Controllers\Admin\UserController;
use App\Models\Task;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes([
    'register' => false,
    'verify' => false,
    'reset' => false
]);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Activity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
    use HasFactory;

    protected $fillable = ['start', 'end', 'description', 'comment', 'task_id'];

    function user() {
        return $this->belongsTo(User::class);
    }

    function task() {
        return $this->belongsTo(Task::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasFactory, HasRoles, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'login',
        'name',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    function tasks() {
        return $this->hasMany(Task::class);
    }

    function projects() {
        return $this->hasMany(Project::class);
    }

    function activities() {
        return $this->hasMany(Activity::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\User\UserCreateRequest;
use App\Models\User;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    function index() {
        //dd(User::with('roles')->get());
        return view('admin.user.index', ['users' => User::with('roles')->get()]);
    }

    function store(UserCreateRequest $request)
    {
        $data = $request->validated();
        $user = User::create($data);
        $user->assignRole(Role::findById($request->getRoleId()));

        return redirect()->route('admin.users.index');
    }

    function create() {
        return view('admin.user.create', ['roles' => Role::all()]);
    }
}

app/Http/Controllers/Manager/UserController.php
<?php

namespace App\Http\Controllers\Manager;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    function index() {
        return view('manager.user.index', ['users' => User::all()]);
    }
}

app/Http/Controllers/User/ActivityController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\User\Activity\ActivityCreateRequest;
use App\Models\Activity;
use App\Models\Task;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ActivityController extends Controller
{
    function create($id) {
        return view('user.activity.create', ['task_id' => $id]);
    }

    function store(ActivityCreateRequest $request) {
        //TODO: привести в человеческий вид
        //dd($request->all());
        $data = $request->validated();
        //$data['user_id'] = Auth::id();
        $data['start'] = Carbon::today()->setTimeFromTimeString($data['start']);
        $data['end'] = Carbon::today()->setTimeFromTimeString($data['end']);
        //dd($data);
        $user = Auth::user();
        $user->activities()->create($data);
        //Activity::create($data);

        return redirect()->route('tasks.index');
    }

    function index($date = null) {
        $user = Auth::user();
        //$tasks = $user->tasks()->with('activities')->whereDate('start', '=', Carbon::today())->get();
        $tasks = $user->tasks()->get();

        return view('user.activity.index', ['tasks' => $tasks, 'users' => User::role('regular')->get(), 'user' => $user]);
    }

    function byUser(Request $request) {
        //dd($request->all());
        $user = User::find($request->user_id);
        //dd($user);
        if (!$user)
            return redirect()->route('activities.index');

        $tasks = $user->tasks()->get();
        return view('user.activity.index', ['tasks' => $tasks, 'users' => User::role('regular')->get(), 'user' => $user]);
    }
}

app/Http/Controllers/User/TaskController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\Task;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TaskController extends Controller
{
    function index() {
        //dd();
        $tasks = Task::currentStatus('pending');
        $tasks = $tasks->where('user_id', '=', Auth::id())->get();
        return view('user.index', ['tasks' => $tasks]);
    }
}

resources/views/user/activity/create.blade.php
@extends('layouts.app')

@section('content')
    <form method="post" action="{{ route('tasks.activity.store', $task_id) }}">
        @csrf
        <input type="hidden" name="task_id" value="{{ $task_id }}">

        <div class="form-group">
        <label for="description">Описание работы</label>
        <textarea class="form-control" name="description" id="description"></textarea>
        </div>

        <div class="form-group">
        <label for="start">С</label>
        <input class="form-control" type="time" name="start" id="start">
        </div>

        <div class="form-group">
        <label for="end">До</label>
        <input class="form-control" type="time" name="end" id="end">
        </div>

        <div class="form-group">
        <label for="comment">Комментарий</label>
        <textarea class="form-control" name="comment" id="comment"></textarea>
        </div>

        <input class="btn btn-primary" type="submit" value="Готово">
        <a class="btn btn-danger" href="{{ route('tasks.index') }}">Отмена</a>
    </form>
@endsection

resources/views/user/activity/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>{{ $user->name }}</h1>
    <form method="get" action="{{ route('activities.index') }}">
        <input type="date" name="date" id="date" value="{{ date('Y-m-d') }}">
        <input class="btn btn-primary" type="submit" value="Показать">
    </form>
    <form method="post" action="{{ route('activities.user') }}">
        @csrf
        <select name="user_id" id="user_id">
            <option value="{{ Auth::id() }}" selected>Я</option>
            @foreach($users as $user)
                <option value="{{ $user->id }}">{{ $user->name }}</option>
            @endforeach
        </select>
        <input class="btn btn-primary" type="submit" value="Показать">
    </form>
    </thead>
    <table class="table">
        <tr>
            <th scope="col">Проект</th>
            <th scope="col">Задача</th>
            <th scope="col">Дедлайн</th>
            {{--<th scope="col">Время работы сегодня</th>--}}
            <th scope="col">Общее время работы</th>
            <th scope="col">Статус задачи</th>
        </tr>
        @foreach($tasks as $task)
            <tr>
                <td>{{ $task->project->title }}</td>
                <td>{{ $task->title }}</td>
                <td>{{ $task->deadline }}</td>
                {{--<td>{{ $task->worktime() }}</td>--}}
                <td>{{ $task->totalWorktime() }}</td>
                <td>{{ $task->status }}</td>
            </tr>
        @endforeach

    </table>
@endsection